wget https://www.kellogg.northwestern.edu/images/students/all/aal659.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/gbd904.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/jbj041.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/aba5846.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mcx7424.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/leh5605.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/lgj969.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/ags558.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/iia862.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/jkb867.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mkd271.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/jkl566.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/nik6447.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mlk7414.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/jdl757.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/wcl354.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/sel550.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/dlu201.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/bmw416.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/bjm8017.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/rnm451.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/dmr7965.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/anm504.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/jnf411.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/ewp5718.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/sjp454.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/mdq293.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/far956.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/pbr516.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/hsd6910.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/jms396.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/tes979.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/sth0464.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/cat2649.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/jtu729.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/djw142.jpg
wget https://www.kellogg.northwestern.edu/images/students/all/caw555.jpg